# Generated by curly apply. Deterministic brace-expansion helper.
# A value with no `{...}` groups always expands to exactly itself, so
# callers that never pass brace syntax see unchanged behavior.
from __future__ import annotations
from itertools import product
from typing import List


class BraceExpandError(ValueError):
    pass


def _split_top_level(text: str, sep: str = ",") -> List[str]:
    parts = []
    depth = 0
    start = 0
    for i, c in enumerate(text):
        if c == "{":
            depth += 1
        elif c == "}":
            if depth == 0:
                raise BraceExpandError("unmatched '}' while splitting brace alternatives")
            depth -= 1
        elif c == sep and depth == 0:
            parts.append(text[start:i])
            start = i + 1
    if depth != 0:
        raise BraceExpandError("unmatched '{' while splitting brace alternatives")
    parts.append(text[start:])
    return parts


def _parse_pieces(text: str):
    pieces = []
    depth = 0
    group_start = None
    literal_start = 0
    for i, c in enumerate(text):
        if c == "{":
            if depth == 0:
                if literal_start < i:
                    pieces.append(("literal", text[literal_start:i]))
                group_start = i
            depth += 1
        elif c == "}":
            if depth == 0:
                raise BraceExpandError(f"unmatched '}}' at position {i}")
            depth -= 1
            if depth == 0:
                content = text[group_start + 1 : i]
                alts = [_parse_pieces(a) for a in _split_top_level(content)]
                pieces.append(("choice", alts))
                literal_start = i + 1
                group_start = None
    if depth != 0:
        raise BraceExpandError(f"unmatched '{{' in {text!r}")
    if literal_start < len(text):
        pieces.append(("literal", text[literal_start:]))
    return pieces


def _expand_pieces(pieces) -> List[str]:
    results = [""]
    for kind, value in pieces:
        next_results = []
        if kind == "literal":
            for prefix in results:
                next_results.append(prefix + value)
        else:
            for prefix in results:
                for alt in value:
                    for expanded in _expand_pieces(alt):
                        next_results.append(prefix + expanded)
        results = next_results
    return results


def expand(token: str) -> List[str]:
    return _expand_pieces(_parse_pieces(token))


def expand_or_literal(token: str) -> List[str]:
    try:
        return expand(token)
    except BraceExpandError:
        return [token]


def cartesian(fields: List[List[str]]) -> List[List[str]]:
    return [list(combo) for combo in product(*fields)] if fields else [[]]
