// Generated by `curly apply`. Deterministic brace-expansion helper.
// A value with no `{...}` groups always expands to exactly itself, so
// callers that never pass brace syntax see unchanged behavior.
#![allow(dead_code)]

#[derive(Debug, Clone, PartialEq)]
enum Piece {
    Literal(String),
    Choice(Vec<Vec<Piece>>),
}

pub fn expand(token: &str) -> Result<Vec<String>, String> {
    let pieces = parse_pieces(token)?;
    Ok(expand_pieces(&pieces))
}

fn parse_pieces(input: &str) -> Result<Vec<Piece>, String> {
    let mut pieces = Vec::new();
    let mut depth: usize = 0;
    let mut group_start: Option<usize> = None;
    let mut literal_start: usize = 0;

    for (i, c) in input.char_indices() {
        match c {
            '{' => {
                if depth == 0 {
                    if literal_start < i {
                        pieces.push(Piece::Literal(input[literal_start..i].to_string()));
                    }
                    group_start = Some(i);
                }
                depth += 1;
            }
            '}' => {
                if depth == 0 {
                    return Err(format!("unmatched '}}' at position {}", i));
                }
                depth -= 1;
                if depth == 0 {
                    let start = group_start.expect("group_start must be set when depth > 0");
                    let content = &input[start + 1..i];
                    let alternatives = split_top_level(content, ',')?;
                    let parsed: Result<Vec<Vec<Piece>>, String> =
                        alternatives.into_iter().map(parse_pieces).collect();
                    pieces.push(Piece::Choice(parsed?));
                    literal_start = i + 1;
                    group_start = None;
                }
            }
            _ => {}
        }
    }

    if depth != 0 {
        return Err(format!("unmatched '{{' in {:?}", input));
    }
    if literal_start < input.len() {
        pieces.push(Piece::Literal(input[literal_start..].to_string()));
    }
    Ok(pieces)
}

fn split_top_level(input: &str, separator: char) -> Result<Vec<&str>, String> {
    let mut parts = Vec::new();
    let mut depth: usize = 0;
    let mut start: usize = 0;

    for (i, c) in input.char_indices() {
        match c {
            '{' => depth += 1,
            '}' => {
                if depth == 0 {
                    return Err("unmatched '}' while splitting brace alternatives".to_string());
                }
                depth -= 1;
            }
            c if c == separator && depth == 0 => {
                parts.push(&input[start..i]);
                start = i + 1;
            }
            _ => {}
        }
    }

    if depth != 0 {
        return Err("unmatched '{' while splitting brace alternatives".to_string());
    }
    parts.push(&input[start..]);
    Ok(parts)
}

fn expand_pieces(pieces: &[Piece]) -> Vec<String> {
    let mut results = vec![String::new()];
    for piece in pieces {
        let mut next = Vec::new();
        match piece {
            Piece::Literal(text) => {
                for prefix in &results {
                    next.push(format!("{}{}", prefix, text));
                }
            }
            Piece::Choice(alternatives) => {
                for prefix in &results {
                    for alt in alternatives {
                        for expanded in expand_pieces(alt) {
                            next.push(format!("{}{}", prefix, expanded));
                        }
                    }
                }
            }
        }
        results = next;
    }
    results
}

/// Expand `token`, falling back to `[token]` unchanged if it fails to parse
/// (e.g. a literal, unrelated use of `{`/`}` in the original value).
pub fn expand_or_literal(token: &str) -> Vec<String> {
    expand(token).unwrap_or_else(|_| vec![token.to_string()])
}

/// Cartesian product of per-argument expansions, in argv order.
pub fn cartesian(fields: &[Vec<String>]) -> Vec<Vec<String>> {
    let mut plans: Vec<Vec<String>> = vec![Vec::new()];
    for field in fields {
        let mut next = Vec::new();
        for prefix in &plans {
            for option in field {
                let mut combined = prefix.clone();
                combined.push(option.clone());
                next.push(combined);
            }
        }
        plans = next;
    }
    plans
}
